apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cosmonic-labs/vcf-demo'
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: 'sample-cluster'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
